FROM openjdk:18-alpine

# Install python/pip
ENV PYTHONUNBUFFERED=1
RUN apk add --update --no-cache python3 && ln -sf python3 /usr/bin/python
RUN python3 -m ensurepip
RUN pip3 install --no-cache --upgrade pip setuptools

# Install spark jars with
RUN pip3 install pyspark[sql]
RUN python3 -c "from pyspark.sql import SparkSession; SparkSession.builder.appName('InstallJars').config('spark.jars.packages','org.apache.spark').getOrCreate()" 
